# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-31 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0002_auto_20190330_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'default_permissions': ('view', 'add', 'change', 'delete', 'export'), 'ordering': ['-actived', '-modified'], 'verbose_name': '机柜信息', 'verbose_name_plural': '机柜信息'},
        ),
    ]
